import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { UserProvider } from "@/utilis/contexts/userContext";

export const metadata: Metadata = {
  title: "Mega Lanches",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="mb-20 md:mb-0 md:mt-20">
        <Header/>
         <UserProvider>
          {children}
         </UserProvider>
      </body>
    </html>
  );
}
